package com.joysistvi.CyberAccess.model;

public class Computers {

    public static final String STATUS_AVAILABLE   = "Available";
    public static final String STATUS_IN_USE      = "In Use";
    public static final String STATUS_MAINTENANCE = "Maintenance";

    private int id;
    private String computerName;
    private String status;

    public Computers() {
    }

    // For new records (id is generated by the database)
    public Computers(String computerName, String status) {
        this.computerName = computerName;
        this.status = status;
    }

    public Computers(int id, String computerName, String status) {
        this.id = id;
        this.computerName = computerName;
        this.status = status;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getComputerName() {
        return computerName;
    }

    public void setComputerName(String computerName) {
        this.computerName = computerName;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return String.format("%-4d %-15s %s", id, computerName, status);
    }
}
