package com.joysistvi.CyberAccess.model;

import java.math.BigDecimal;

public class Rates {

    public static final String STATUS_ACTIVE   = "Active";
    public static final String STATUS_INACTIVE = "Inactive";

    private int id;
    private int serviceId;
    private String rateName;
    private String rateType;   // Computer, Printing, Photocopy, ...
    private BigDecimal price;
    private String unit;       // per hour, per page, ...
    private String status;

    public Rates() {
    }

    // For new records (id is generated by the database)
    public Rates(int serviceId, String rateName, String rateType, BigDecimal price, String unit, String status) {
        this.serviceId = serviceId;
        this.rateName = rateName;
        this.rateType = rateType;
        this.price = price;
        this.unit = unit;
        this.status = status;
    }

    public Rates(int id, int serviceId, String rateName, String rateType, BigDecimal price, String unit, String status) {
        this(serviceId, rateName, rateType, price, unit, status);
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getServiceId() {
        return serviceId;
    }

    public void setServiceId(int serviceId) {
        this.serviceId = serviceId;
    }

    public String getRateName() {
        return rateName;
    }

    public void setRateName(String rateName) {
        this.rateName = rateName;
    }

    public String getRateType() {
        return rateType;
    }

    public void setRateType(String rateType) {
        this.rateType = rateType;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return String.format("%-4d %-28s %-12s %8s %-10s %s",
                id, rateName, rateType, price.toPlainString(), unit, status);
    }
}
